### ISSUE TITLE
Front end implementation notes

### ISSUE THREAD

**Issue by flukeout** [mozilla/womenandweb#26]
Thoughts I'm having as I go along...
- Not a fan of these `.p-y-3` and `.m-x-3` classes
  - Why are their rules `!important`?
  - Mostly I just want to ditch them, but not sure if that has some unforseen repercussions
  - The difference between a `2` and `3` is often too big
- The indented HTML style is hard to work with, especially when borrowing markup from existing properties (like for the footer)
- Hard to implement proper footer styling, even though it exists in a few places
  - Tried taking markup and CSS from the Science site
  - Had to copy over a few SCSS variables in the process
  - Would like a one-stop-shop link or copy & paste source for complete footer styling
- When adding new images to a subfolder in the `/images` folder the server needs a manual restart for the image to be available to the front end
- Several times I've "lost" images, they've either reverted to a previous version or disappeared entirely. Not sure how to reproduce. Could it be something in the build process?

**Comment by gvn** [comment]
> - Not a fan of these `.p-y-3` and `.m-x-3` classes

They are part of Bootstrap, so we should be using them whenever possible because they're designed for its grid.

> - The indented HTML style is hard to work with, especially when borrowing markup from existing properties (like for the footer)

It's a trade off for getting to write concise templates when you're not copy-pasting stuff (which we shouldn't do unless we have to). If we're finding we need to reuse stuff we should make shared libraries instead of just copying it (D.R.Y. principle).

> - When adding new images to a subfolder in the `/images` folder the server needs a manual restart for the image to be available to the front end

I should be able to fix this. Can you file a ticket?

> - Several times I've "lost" images, they've either reverted to a previous version or disappeared entirely. Not sure how to reproduce. Could it be something in the build process?

Were you adding them directly to the `dest` folder? Anything inside it can get overwritten and it should never be edited manually.

**Comment by gvn** [comment]
@flukeout – I just tried to repro adding a new image and when `npm start` was running it did pick it up and copy it to the `source`. I was also able to access it through the test server in the browser without restarting. Were you adding them to `source/images/`?
