### ISSUE TITLE
Create github markdown templates for WWL

### ISSUE THREAD

**Issue by amirad** [mozilla/womenandweb#38]
I want to create easy to share report templates in github - like we did for web lit https://mozilla.github.io/content/web-lit-whitepaper/ 

The template above looks great to use - @flukeout anything I need to know or do before adapting it for WWL?

**Comment by ldecoursy** [comment]
New internal monthly reporting template (in github) is coming your way later this week :)

**Comment by flukeout** [comment]
@ldecoursy what are these templates that you are talking about, will you be able to use it for 
@amira's content?

Here is the content Amira needs converted...
- [Understanding Women & Web Lit](https://docs.google.com/document/d/14n3YHUp-3LuS36SHpMAIGHlF6nwQLnoATKSooLmerqA/edit#)
- [Understanding Cyberviolence](https://docs.google.com/document/d/17sAumfVOSsveY6tu58fuzek053_rcxmO1XdZCLaAxps/edit#)
- [Women & Web Literacy](https://docs.google.com/document/d/12O_DzleTZVOief1gUas2RlPE8AsxS6fHU36CRVriIl8/edit#heading=h.vvv9h172hmc1)

**Question** - What hub or section would these belong to, branding & identity wise? The Web Lit map whitepaper has an orange theme because the Web Literacy section of the Learning site is orange. Should we brand these whitepapers with the Clubs purple we've been using? Or do we want a more generic "MoFo Whitepaper" style. I'll put this question to the design team as well.

**Question 2** - Is converting these required for launch? Can we make the Google Docs readable by public? Or maybe convert them to PDFs and link those?

**Comment by ldecoursy** [comment]
Ignore me, I misunderstood. I was talking about internal reporting templates, but now realize this is referring to research reports for public consumption ;)

**Comment by flukeout** [comment]
Closing, as for now we're linking to PDFs exported from the Google Docs. Can tackle hosting them via the github templates after launch in another issue.
