### ISSUE TITLE
Post-mortem / Debrief

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/womenandweb#47]
Based on the project and its timeline outlined here: https://github.com/MozillaFoundation/plan/issues/826, we should talk a little bit about what we can learn from the whole experience.

It would be awesome if @flukeout, @gvn, @hannahkane, @amirad and @kaythaney would share their thoughts that might help inform how we approach future projects similar to this. This is not a requirement at all so if you think that your thoughts are captured by other comments, it's ok to not repeat.

Some things you can comment on could be:
- The development process
- The QA process
- Defining the scope of the project
- Stakeholder communication
- Team communication
- Determining the timeline
- Parallelization of work
- etc.

You could talk about any/all of this and anything else you would like to add (things we did right as well as things we did wrong along with suggestions on how we can improve).

cc @simonwex and @xmatthewx

**Comment by hannahkane** [comment]
What worked well:
- Design and dev phases were both speedy, but didn't feel overly rushed
- Feedback and QA from stakeholders was super quick
- Project management felt solid; organized and efficient, with good communication all around
- Lightweight tech solution seems a good match for the emergent nature of the project
- Page looks great

What was challenging + possible fixes:
- I felt the initial scoping conversations were a bit confusing. It was hard to isolate the particular requirements for this project from the larger programmatic questions (e.g. "how does WWL hub relate to Learning hub?"), as well as separate the timeline for this particular project from broader concerns about longer-term capacity as new project requirements emerge. I think the solution we came up with addresses both of these fuzzy areas pretty well—by fully divorcing WWL from the Learning hub, and by hosting it on a github page, we're making it easier on our future selves to evolve the web presence as needed.

**Comment by kaythaney** [comment]
Thanks, Gideon! 

My feedback:

What worked well: 
- Content draft + iterations went smoothly. Having that in hand helped get this moving and brought clarity to the needs of the page. 
- QA was super fast + rich. Loved the clarity in process and quick refinement. 
- Github page approach helped this move forward quickly while still keeping design aligned and consistent. Seemed to make for a more nimble build, which was appreciated! 

What was challenging + suggested improvements:
- Technical decisions vs editorial decisions felt conflated at times, and added strain. Wires crossed there a bit, re: desire for easier build + edit access using gh-pages versus cms (clarity came mid-process there on the cms). Also, confusion re: domain name - where decision on whether the program warranted moving to a primetime domain (which was an editorial decision already made) seemed conflated with the technical ease in changing a domain name/pushing a redirect. Led to us talking past each other more than working towards a common solution and brainstorming togheter. That could have been set up better, so that decision making was less murky, and so we were working creatively within constraints, rather than rolling back decisions on namespace. Hannah's update on using gh-pages vs the CMS also came midway through this work, which would have helped to know at the outset as a number of us were operating with different expectations.
- Would suggest more regular checkins between Hannah + myself to help make that decision making process even more transparent for MLN, and _big fan_ of these debriefs. That initial meeting likely needed an additional debrief as well, as there were a number of other tensions that surfaced - many re: work separate from the WWL needs (ie., learning.mozilla.org plans, roadmapping / workload in general, decision making etc). Still unpacking, but worth naming. :)

Big thanks again, all!

**Comment by simonwex** [comment]
Some good comments and insights here. To cherry-pick one of @kaythaney's suggestions on checkins: I think @hannahkane's involvement in the MLN directors calls would be a great place to start.  The next two have very relevant items in the agenda, I'll reach out to Lainie.

**Comment by gvn** [comment]
I was very pleased with how this all came together from a design & build perspective! Nice work, all.

My only lingering concern is the choice to not have a staging environment and instead promote any edits directly to production. I think this is acceptable for the moment, as we're just getting started, but should be revisited as we begin to scale.

**Comment by kaythaney** [comment]
Great point on the staging environment, @gvn. 

And +1 to @simonwex 's suggestion. To build on that, @hannahkane - would love to find a time outside of those meetings to be in more regular communication to support your work. Let me know what'd work best!

**Comment by flukeout** [comment]
Went well from my perspective. I got content, assets and feedback quickly which made the process smooth.

**Let's test content updating!**
We made the assumption that the content would be easy to update by non-devs, so let's test that as soon as we can. @amirad - will you be updating the content in the future? If so, let's jump on a call and make some trivial changes to see how it goes.

**Comment by gideonthomas** [comment]
I'm going to do a bad job summarizing/condensing the really well made points above but I'm going to try anyway (Thank you very much to all who contributed to this debrief :) ) :P

## What Worked Well
- Project was completed in a speedy, smooth and timely manner
- QA process was concise and effective
- Simple solution that suited the needs, not over-engineered

## What can be Improved
- Communication between Program staff and Product staff needs more synchronicity
- More regular check-ins between @hannahkane and @kaythaney 
- Having more explicit guidelines on when we need a staging environment vs. when it can be bypassed

cc @simonwex (what would be a good place to archive this so that we can refer this report later?)

**Comment by hannahkane** [comment]
@gideonthomas - mofo.build might be a good place to archive.

**Comment by amirad** [comment]
Sorry for the delay while traveling! 
The summaries look great and cover much of what I would have said anyways. My only other to add on the what worked well was: 
*knowing and having Gideon as manager from start to end
*doing this debrief 

Also, @flukeout I actually need to update a few things in the next week so will give feedback really soon!

**Comment by gideonthomas** [comment]
@amirad Thanks! And thanks for being so prompt with QA, content, feedback, etc.; it made the process really smooth.

@hannahkane do you know who I would talk to to get this content on there? Matt maybe?

**Comment by hannahkane** [comment]
Just added you as an Admin, @gideonthomas.

**Comment by amirad** [comment]
@flukeout yesterday I updated a post, added resources, changed text and re-ordered some of the logos! Everything was easy-peasy and worked well for me!
