### ISSUE TITLE
OG Image is still "TODO"

### ISSUE THREAD

**Issue by gvn** [mozilla/womenandweb#57]
We should add an OG Image (primarily for when people share the site on Facebook).

https://github.com/mozilla/womenandweb/blob/master/source/index.pug#L13

**Comment by hannahkane** [comment]
Can we use an untreated (or differently-treated) version of the image in the hero?

**Comment by gvn** [comment]
Sure. Here's the best practices: https://developers.facebook.com/docs/sharing/best-practices#images

We'll probably want a designer to create this image.

**Comment by hannahkane** [comment]
@sabrinang - is this something you might have time for? It it not more urgent than Network stuff. :)

**Comment by sabrinang** [comment]
@hannahkane I can work on this next week

**Comment by sabrinang** [comment]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/2492510/27059646-7299b6dc-4f8c-11e7-9293-b5d9a53238f5.png">

@hannahkane Do we keep the previous styling for the thumbnail or should we update with the new brand (but it won't match the site)? and is there a preference if we want to include a description of wwl on the image?

**Comment by gvn** [comment]
I'd suggest not putting the description in the image (but we should put it in the og:description tag!), because it'll be redundant.

FYI, here's what it currently looks like on Facebook:

<img width="396" alt="screen shot 2017-06-12 at 4 50 50 pm" src="https://user-images.githubusercontent.com/206379/27060111-72ee1ddc-4f8f-11e7-94c8-8e2ea81a0cd3.png">

PS: Typo in the bottom 2: "Woman" should be "Women". ;)

**Comment by sabrinang** [comment]
Thanks @gvn for catching the typo and no description sounds good when it is in context of the post.

**Comment by sabrinang** [comment]
I brought up the branding topic up at design crit today. The best solution would be to just use a photo to avoid it for now and photos typically perform better on social. I narrowed it down to two from the site: 
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/2492510/27243554-5b233a88-5297-11e7-8160-f15a69092171.png">

But I'm thinking we should go with the group picture on the right because the people are engaging with the camera and it feels more inviting.
 
Mockup:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/2492510/27244030-91dac134-5299-11e7-87e9-9fcbc5223394.png">

Image:
![photo-wwl 2x](https://user-images.githubusercontent.com/2492510/27243742-2ccf34ce-5298-11e7-971d-6db7db1d17cc.jpg)

**Comment by gvn** [comment]
That sounds good to me. I can also change the description over to "Working towards an open, safe, and innovative web for women everywhere." so it's not redundant with WWL in there twice.

**Comment by hannahkane** [comment]
+1 to all of this.
